// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Axios = require("axios");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("ChildrenProps");

function make(githubName, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */(function (self) {
              Axios.get("https://api.github.com/users/" + githubName).then((function (response) {
                        return Promise.resolve(Curry._1(self[/* send */3], /* SetData */[response.data.avatar_url]));
                      })).catch((function () {
                      return Promise.resolve(Curry._1(self[/* send */3], /* SetError */0));
                    }));
              return self[/* state */1];
            }),
          /* didMount */(function (self) {
              Axios.get("https://api.github.com/users/" + githubName).then((function (response) {
                        return Promise.resolve(Curry._1(self[/* send */3], /* SetData */[response.data.avatar_url]));
                      })).catch((function () {
                      return Promise.resolve(Curry._1(self[/* send */3], /* SetError */0));
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return Curry._2(children, self[/* state */1][/* avatar_url */0], self[/* state */1][/* error */1]);
            }),
          /* initialState */(function () {
              return /* record */[
                      /* avatar_url */"",
                      /* error */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[
                            /* avatar_url */action[0],
                            /* error */""
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* avatar_url */"",
                            /* error */"Error"
                          ]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
